### ISSUE TITLE
Flow encoder or decoder?

### ISSUE THREAD

**Issue by ZHOUYI1023** [Toytiny/RaFlow#1]
In your paper, section III.B, you call the third layer as flow encoder, but in the figure and the code, you mention it as flow decoder.

**Comment by Toytiny** [comment]
Thanks for your comment. The third layer,  used to extract features on embeddings and parse scene flow with point-based MLP, should be called "Flow Decoder".  In our arxiv version, we misspelt this single word and feel sorry for your misunderstanding of it.

**Comment by Toytiny** [comment]
> In your paper, section III.B, you call the third layer as flow encoder, but in the figure and the code, you mention it as flow decoder.

Thanks for your comment. The third layer,  used to extract features on embeddings and parse scene flow with point-based MLP, should be called "Flow Decoder".  In our arxiv version, we misspelt this single word and feel sorry for your misunderstanding of it.
