### ISSUE TITLE
Paper implementation

### ISSUE THREAD

**Issue by mdane-x** [Toytiny/RaFlow#2]
Great work, thank you for sharing!

Will the code be open-sourced?

**Comment by Toytiny** [comment]
Thanks for your attention!

Our code will be released to the community before publication.

I will keep this issue open, and close it when it is added, so you will get notified as well.

**Comment by Toytiny** [comment]
> Great work, thank you for sharing!
> 
> Will the code be open-sourced?

Hi, our code with demo data has been released.
If you have any questions about it, feel free to tell us.
